name: Continuous Integration
on: [ push, pull_request ]

jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.x ]
        platform: [ ubuntu-latest ]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - uses: golangci/golangci-lint-action@v3

      - name: Run lint
        run: make lint
      - name: Run go test
        run: make test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
